### ISSUE TITLE
Text of Tabs disappears on Overview Page 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/neurolab-android#546]
Some text of tabs disappears on Overview Page in some resolutions.

![6105308749889536_1575317251_Screenshot_20191203-013619_NeuroLab](https://user-images.githubusercontent.com/1583873/69992520-1f976480-154a-11ea-9bd8-7844450b2e62.jpg)

**Comment by dheerajkotwani** [comment]
can i work on this issue?

**Comment by jddeep** [comment]
@dheerajkotwani Go ahead :+1:

**Comment by annkkiit** [comment]
can i work on this?

**Comment by dheerajkotwani** [comment]
@ankit2019j I was working on this, and the issue is solved.

**Comment by annkkiit** [comment]
> @ankit2019j I was working on this, and the issue is solved.

okay

**Comment by ho-dor** [comment]
This issue is still not solved. I will be working on this @mariobehling @jddeep .
